# Git shortcuts - Add these to ~/.bashrc or ~/.zshrc
alias gl='git log --oneline --graph --decorate'
alias gs='git status'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gcm='git commit -m'
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gds='git diff --staged'
alias gco='git checkout'
alias gst='git stash'
alias gstp='git stash pop'
alias glg='git log --oneline --all --graph --decorate'
alias grh='git reset HEAD'
alias gcl='git clone'
alias gf='git fetch'
alias gm='git merge'
alias gt='git tag'
alias gta='git tag -a'
alias gr='git remote -v'
alias gra='git remote add'
alias glog='git log --pretty=format:"%C(auto)%h %C(green)%ad %C(blue)%s %C(yellow)%an" --date=short'
