"""LangGraph agent state model using typed Pydantic models.

The state captures conversation history, classified intent, tool call
results, and final response. Models are independent of specific tool
implementations so new tools can be added without restructuring state.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field

from services.agent.intents import ClassifiedIntent, IntentType


class Message(BaseModel):
    """Single message in the agent conversation history."""

    role: str = Field(pattern="^(user|assistant|system|tool)$")
    content: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolCallRequest(BaseModel):
    """A request to invoke a specific agent tool."""

    tool_name: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class ToolCallResult(BaseModel):
    """Result returned from a tool invocation."""

    tool_name: str
    success: bool
    data: Any = None
    error: Optional[str] = None


class AgentResponse(BaseModel):
    """Final response generated by the agent for the user."""

    answer: str
    intent: IntentType
    sources: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)


class AgentState(BaseModel):
    """Complete state model for the LangGraph Data Engineer Agent.

    Captures the full lifecycle of an agent interaction:
    question → intent → tool calls → response.

    The state is serializable and independent of specific tool
    implementations.
    """

    question: str
    messages: list[Message] = Field(default_factory=list)
    classified_intent: Optional[ClassifiedIntent] = None
    tool_calls: list[ToolCallRequest] = Field(default_factory=list)
    tool_results: list[ToolCallResult] = Field(default_factory=list)
    response: Optional[AgentResponse] = None
    errors: list[str] = Field(default_factory=list)
