apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ai-data-platform.namespace" . }}
  labels:
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/managed-by: helm
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
