apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ai-data-platform
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: ai-data-platform
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
