apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ai-data-platform
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: kafka
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ai-data-platform
  ports:
    - port: 29092
      targetPort: 29092
      nodePort: 30092
      protocol: TCP
      name: internal
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: external
