{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ include "ai-data-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: airflow-webserver
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: airflow
spec:
  type: {{ .Values.airflow.webserver.service.type }}
  ports:
    - port: {{ .Values.airflow.webserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.airflow.webserver.service.nodePort }}
      nodePort: {{ .Values.airflow.webserver.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: airflow-webserver
    app.kubernetes.io/part-of: ai-data-platform
{{- end }}
