apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ include "ai-data-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ai-data-platform
  ports:
    - port: {{ .Values.kafka.service.internalPort }}
      targetPort: {{ .Values.kafka.service.internalPort }}
      protocol: TCP
      name: internal
    - port: {{ .Values.kafka.service.externalPort }}
      targetPort: {{ .Values.kafka.service.externalPort }}
      nodePort: {{ .Values.kafka.service.nodePort }}
      protocol: TCP
      name: external
