apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: {{ include "ai-data-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: database-credentials
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: secrets
type: Opaque
data:
  db-password: {{ .Values.secrets.database.password | quote }}
