apiVersion: v1
kind: Secret
metadata:
  name: ingestion-api-keys
  namespace: {{ include "ai-data-platform.namespace" . }}
  labels:
    app.kubernetes.io/name: ingestion-api-keys
    app.kubernetes.io/part-of: ai-data-platform
    app.kubernetes.io/component: secrets
type: Opaque
data:
  bestbuy-api-key: {{ .Values.secrets.ingestion.bestbuyApiKey | quote }}
